<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2026 Robert Bosch Manufacturing Solutions GmbH
  ~
  ~ See the AUTHORS file(s) distributed with this work for additional
  ~ information regarding authorship.
  ~
  ~ This Source Code Form is subject to the terms of the Mozilla Public
  ~ License, v. 2.0. If a copy of the MPL was not distributed with this
  ~ file, You can obtain one at https://mozilla.org/MPL/2.0/.
  ~
  ~ SPDX-License-Identifier: MPL-2.0
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <parent>
      <groupId>org.eclipse.esmf</groupId>
      <artifactId>esmf-sdk-parent</artifactId>
      <version>2.16.0</version>
      <relativePath>../../pom.xml</relativePath>
   </parent>

   <artifactId>esmf-sdk-bom</artifactId>
   <name>ESMF SDK Bill of Materials</name>
   <packaging>pom</packaging>

   <dependencyManagement>
      <dependencies>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-interface</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-meta-model-java</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-aas-generator</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-document-generators</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-generator</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-github-resolver</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-importers</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-jackson</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-java-core</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-java-generator</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-urn</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-model-validator</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-aspect-static-meta-model-java</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-test-aspect-models</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-test-resources</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-tree-sitter-turtle</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-turtle-language-server</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>org.eclipse.esmf</groupId>
            <artifactId>esmf-util</artifactId>
            <version>${project.version}</version>
         </dependency>
      </dependencies>
   </dependencyManagement>

   <build>
      <plugins>
         <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>flatten-maven-plugin</artifactId>
            <version>${flatten-maven-plugin.version}</version>
            <configuration>
               <flattenMode>bom</flattenMode>
               <pomElements>
                  <properties>remove</properties>
               </pomElements>
            </configuration>
            <executions>
               <execution>
                  <id>flatten</id>
                  <goals>
                     <goal>flatten</goal>
                  </goals>
                  <phase>process-resources</phase>
               </execution>
               <execution>
                  <id>flatten.clean</id>
                  <goals>
                     <goal>clean</goal>
                  </goals>
                  <phase>clean</phase>
               </execution>
            </executions>
         </plugin>
      </plugins>
   </build>
</project>
