:page-partial:

[[samm-cli]]
= SAMM CLI

The SAMM CLI is a command line tool for the validation of Aspect Models and the generation of artifacts, such as documentation or code, from Aspect Models.

TIP: Download latest version: icon:download[] https://github.com/eclipse-esmf/esmf-sdk/releases/download/v{esmf-sdk-version}/samm-cli-{esmf-sdk-version}.jar[samm-cli-{esmf-sdk-version}.jar]

NOTE: For technical reasons, Java 17 or newer is required to successfully run the tool.

[[samm-cli-getting-started]]
== Running the SAMM CLI

For the executable jar, call `java -jar samm-cli-{esmf-sdk-version}.jar` followed by one of the following subcommands (e.g., `java -jar samm-cli-{esmf-sdk-version}.jar help`).
In the following sections, `samm` will be used as the command name.

[TIP]
====
To make `samm-cli` easier to call, you can add an alias to the configuration of the shell of your choice.
For example, for Bash, you could add the following line to `.bashrc`:

[source,shell,subs="attributes+,+quotes"]
----
alias samm='java -jar /location/to/samm-cli-{esmf-sdk-version}.jar'
----
====

Successful execution of a command is signaled by returning 0. In case of logical or some other internal problem error code 1 is returned.
Missing or wrong command parameters result in error code 2 being returned.

To get help for a certain subcommand, add 'help' before the subcommand name or add `--help` to the end, e.g., `samm help aspect`
or `samm aspect --help`.
Each subcommand can have its own set of options which allow the user to further fine-tune the execution of the command.
The available options and their meaning can also be seen in the help text of the individual subcommands.

[width="100%",options="header",cols="20,50,30"]
|===
| Command | Description/Options | Examples
| help                                  | Get overview of all commands                                   | `samm help`
| help <subcommand>                     | Get help for a specific subcommand                             | `samm help aspect`
| aspect help <aspect subcommand>       | Get help for `aspect` subcommands                              | `samm aspect help validate`
.2+| aspect <model> validate            | Validate Aspect Model                                          | `samm aspect AspectModel.ttl validate`
| _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl validate --custom-resolver myresolver.sh`
.2+| aspect <model> prettyprint         | Pretty-print Aspect Model                                      | `samm aspect AspectModel.ttl prettyprint`
|   _--output, -o_ : the output will be saved to the given file  | `samm aspect AspectModel.ttl prettyprint -o c:\Results\PrettyPrinted.ttl`
.2+| aspect <model> migrate             | Migrate Aspect Model to the latest SAMM version                | `samm aspect AspectModel.ttl migrate AspectModel.ttl`
|    _--output, -o_ : the output will be saved to the given file | `samm aspect AspectModel.ttl migrate AspectModel.ttl -o c:\Results\MigratedModel.ttl`
.5+| aspect <model> to html             | Generate HTML documentation for an Aspect Model                | `samm aspect AspectModel.ttl to html`
|    _--output, -o_ : the output will be saved to the given file | `samm aspect AspectModel.ttl to html -o c:\Model.html`
|    _--css, -c_ : CSS file with custom styles to be included in the generated HTML documentation | `samm aspect AspectModel.ttl to html -c c:\styles.css`
|    _--language, -l_ : The language from the model for which the HTML should be generated (default: en) | `samm aspect AspectModel.ttl to html -l de`
| _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl to html --custom-resolver myresolver.bat`
.4+| aspect <model> to png              | Generate PNG diagram for Aspect Model                          | `samm aspect AspectModel.ttl to png`
|    _--output, -o_ : output file path (default: stdout); as PNG is a binary format, it is strongly recommended to output the result to a file by using the -o option or the console redirection operator '>')|
                                        |    _--language, -l_ : the language from the model for which the diagram should be generated (default: en)|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl to png --custom-resolver resolver.jar`
.4+| aspect <model> to svg              | Generate SVG diagram for Aspect Model                          | `samm aspect AspectModel.ttl to svg`
                                        |    _--output, -o_ : the output will be saved to the given file |
                                        |    _--language, -l_ : the language from the model for which the diagram should be generated (default: en)|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl to svg --custom-resolver "java -jar resolver.jar"`
.4+| aspect <model> to dot              | Generate https://graphviz.org/doc/info/lang.html[DOT] diagram for Aspect Model                          | `samm aspect AspectModel.ttl to dot`
                                        |    _--output, -o_ : output file path (default: stdout)         |
                                        |    _--language, -l_ : the language from the model for which the diagram should be generated (default: en)|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.8+| aspect <model> to java             | Generate Java classes from an Aspect Model                     | `samm aspect AspectModel.ttl to java`
                                        |  _--output-directory, -d_ : output directory to write files to (default: current directory)|
                                        |  _--package-name, -pn_ : package to use for generated Java classes| `samm aspect AspectModel.ttl to java -pn org.company.product`
                                        |  _--no-jackson, -nj_ : disable https://github.com/FasterXML/jackson[Jackson] annotation generation in generated Java classes|
                                        |  _--template-library-file, -tlf_ : the path and name of the https://velocity.apache.org/[Velocity] template file containing the macro library|
                                        |  _--execute-library-macros, -elm_ : Execute the macros provided in the https://velocity.apache.org/[Velocity] macro library|
                                        |  _--static, -s_ : generate Java domain classes for a Static Meta Model|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.13+| aspect <model> to openapi         | Generate https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification for an Aspect Model             | `samm aspect AspectModel.ttl to openapi -j`
                                        |  _--output, -o_ : output file path (default: stdout)           |
                                        |  _--api-base-url, -b_ : the base url for the Aspect API used in the https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification| `samm aspect AspectModel.ttl to openapi -j -b \http://mysite.de`
                                        |  _--json, -j_ : generate a JSON specification for an Aspect Model (default format is YAML)|
                                        |  _--comment, -c_ : only in combination with --json; generates `$comment` OpenAPI 3.1 keyword for all `samm:see` attributes|
                                        |  _--parameter-file, -p_ : the path to a file including the parameter for the Aspect API endpoints| For detailed description, see the section bellow
                                        |  _--semantic-version, -sv_ : use the full semantic version from the Aspect Model as the version for the Aspect API|
                                        |  _--resource-path, -r_ : the resource path for the Aspect API endpoints| For detailed description, see the section bellow
                                        |  _--include-query-api, -q_ : include the path for the Query Aspect API Endpoint in the https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification|
                                        |  _--paging-none, -pn_ : exclude paging information for the Aspect API Endpoint in the https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification|
                                        |  _--paging-cursor-based, -pc_ : in case there is more than one paging possibility, it has to be cursor based paging|
                                        |  _--paging-offset-based, -po_ : in case there is more than one paging possibility, it has to be offset based paging|
                                        |  _--paging-time-based, -pt_ : in case there is more than one paging possibility, it has to be time based paging|
                                        |  _--language, -l_ : The language from the model for which an OpenAPI specification should be generated (default: en) |  `samm aspect AspectModel.ttl to openapi -l de`|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.3+| aspect <model> to json             | Generate example JSON payload data for an Aspect Model        | `samm aspect AspectModel.ttl to json`
                                        |  _--output, -o_ : output file path (default: stdout)           |
| _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.3+| aspect <model> to schema           | Generate JSON schema for an Aspect Model                       | `samm aspect AspectModel.ttl to schema`
                                        |  _--output, -o_ : output file path (default: stdout)           |
                                        |  _--language, -l_ : The language from the model for which a JSON schema should be generated (default: en) |  `samm aspect AspectModel.ttl to schema -l de`|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.4+| aspect <model> to aas              | Generate Asset Administration Shell (AAS) submodel template for an Aspect Model  | `samm aspect AspectModel.ttl to aas`
                                        |  _--output, -o_ : output file path (default: stdout)           |
                                        |  _--format, -f_ : output file format (xml or aasx, default: xml)|
| _--custom-resolver_ : use an external resolver for the resolution of the model elements |
|===

=== Custom model resolver

To allow the users to provide their own custom implementations of a model resolver, `--custom-resolver` command-line switch can be used.
The value of the switch can be any command which is directly executable by the underlying operating system (such as a batch script on Windows or a shell script on Linux/Unix).
When a model element needs to be resolved, this command is executed with the URN of the element to resolve passed as the last parameter.
The command can provide other parameters as well, the element URN will be added automatically as the last one by samm-cli.
The resolved model definition is expected to be output to the stdout in Turtle format.
From there, it is read by the samm-cli and passed on to the internal processing pipeline.
In this way the extension can be flexibly done in any programming language/script language, including complex logic if necessary.

== Using the CLI to create a JSON OpenAPI Specification

Every specification is based on one Aspect, which needs a separately defined server URL where the given aspect will be.
The URL will be defined as string with the `-b` option, i.e.: https://www.example.org.
The default URL, using the above defined --api-base-url, would result in https://www.example.org/api/v1/\{tenantId}/<aspectName>.
By default the Aspect's local name is used as path.
The default path can be manipulated with the `--resource-path` switch.
If the path is defined further, for example `--resource-path "/resources/\{resourceId}"`, the resulting URL would be: https://www.example.org/api/v1/\{tenantId}/resources/\{resourceId}.

It will be required to specify the parameter, in case there is an additional parameter defined.
This has to be in JSON or in YAML, depending on the kind of specification chosen.
For example:
With the option `--resource-path "/resources/\{resourceId}"` the generator constructs the URL https://www.example.org/api/v1/\{tenantId}/resources/\{resourceId}
and then the `--parameter-file` defines the parameter resourceId in yaml:

----
resourceId:
  name: resourceId
  in: path
  description: An example resource Id.
  required: true
  schema:
    type: string
----

The full command would result in:

[source,shell,subs="attributes+,+quotes"]
----
java -jar samm-cli-{esmf-sdk-version}.jar aspect _AspectModel.ttl_ to openapi -b "https://www.example.org" -r "/resources/\{resourceId}" -p _fileLocation_
----

=== Mapping between the Aspect Models and the OpenAPI Specification

In this section, a detailed description of the mapping between individual Aspect elements and the OpenAPI specification is given.
To make it easier to follow, the mapping is explained based on a concrete example, divided into logically coherent blocks.
Please bear in mind that these blocks are snippets or fragments of a larger whole; viewed in isolation they do not necessarily form a valid or meaningful Aspect Model or OpenAPI specification.

==== Naming and versioning

Please consider the following model fragment, with the attention focused on the numbered elements:

----
@prefix samm: <urn:samm:org.eclipse.esmf.samm:meta-model:2.0.0#> .
@prefix : <urn:samm:com.mycompany.myproduct:2.0.0#> . <1>

:Test a samm:Aspect; <3>
    samm:preferredName "TestAspect"@en ; <2>
    samm:preferredName "TestAspekt"@de .
----

<1> prefix used to build the full URN of :Test Aspect
<2> the preferred name of the Aspect in language of user's choice
<3> the name of the Aspect

For the generated OpenAPI Specification, the following mapping would apply:

[source,JSON]
----
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "TestAspect", // <2> <3>
    "version" : "v2" // <1>
  }
}
----

<1> depending on parameters used when generating the specification, this is either the major version of the full Aspect URN (*2*.0.0), or it can be the full version (`v2.0.0`), if using `-sv` (semantic version) command line switch
<2> if present, `samm:preferredName` is used as the value for the `title` element of the specification
<3> as `samm:preferredName` is an optional element, in cases when it is missing the name of the Aspect is used instead

The version information as described above is also used in the URL definitions of the `servers` block of the specification:

[source,JSON]
----
{
 "servers" : [ {
    "url" : "http://mysite/api/v2", // <1>
    "variables" : {
      "api-version" : {
        "default" : "v2" // <1>
      }
    }
  } ]
}
----

The name of the Aspect is used to generate several important OpenAPI artifacts, like the path definitions for the API:

[source,JSON]
----
{
 "paths" : {
    "/{tenant-id}/test" : { // <3>
      "get" : {
        "tags" : [ "Test" ], // <3>
        "operationId" : "getTest" // <3>
      }
    }
  }
}
----

and the definitions for request bodies and responses in the corresponding blocks (`requestBodies` and `responses`) of the OpenAPI specification (example omitted for simplicity).

==== Mapping of Aspect and its properties

For each Aspect in the model, an entry in the `components/schemas` part of the OpenAPI specification is generated.
For an example Aspect from the following fragment:

----
:Test a samm:Aspect; <1>
    samm:properties (
        :prop1 <2>
        [ samm:property :prop2; samm:payloadName "givenName"; ] <3>
        [ samm:property :prop3; samm:optional true; ] ). <4>

:prop1 a samm:Property;
    samm:description "Description of Property1"@en; <5>
    samm:characteristic :Enum. <6>
----

an entry like the one given in the following JSON will be generated:

[source,JSON]
----
"Test" : { // <1>
  "type" : "object",
    "properties" : {
      "prop1" : { // <2>
        "description" : "Description of Property1", // <5>
        "$ref" : "#/components/schemas/urn_samm_test_2.0.0_Enum" // <6>
      },
      "givenName" : { // <3>
        "$ref" : "#/components/schemas/urn_samm_test_2.0.0_EntityChar"
      },
      "prop3" : { // <4>
        "$ref" : "#/components/schemas/urn_samm_test_2.0.0_StringCharacteristic"
      }
    },
    "required" : [ "prop1", "givenName" ] // <2> <3>
}
----

<1> the name of the Aspect is used to name the schema object for the aspect
<2> with plain property references, the name of the property is used to name the property definition
<3> in cases where a payload name is defined on a specific property, it is used in preference to the plain property name
<4> if the property use is also defined as optional, the property will not be included in the list of the required properties
<5> the values of `samm:description` elements in property definitions are included in the generated JSON
<6> for each of the properties characteristics an entry in `components/schemas` is generated and referenced here; if the characteristic is of complex type, the whole procedure is applied recursively to the complex type's properties

==== Mapping of Aspect's operations

If the Aspect also has a non-empty list of operations defined, like the one in the following example:

----
:AspectWithOperation a samm:Aspect ;
   samm:properties ( ) ;
   samm:operations ( :testOperation ) .

:testOperation a samm:Operation ;
   samm:input ( :input ) ; <1>
   samm:output :output . <2>

:output a samm:Property ;
   samm:characteristic samm-c:Text . <3>

:input a samm:Property ;
   samm:characteristic samm-c:Text . <4>
----

then additional entries are added to the generated OpenAPI specification.
First, there is an additional entry in the `paths` section of the specification: `/{tenant-id}/aspect-with-operation/*operations*`.
The available operations are then added to the `components/schemas` part:

[source,JSON]
----
{
 "Operation" : {
    "allOf" : [ {
      "$ref" : "#/components/schemas/JsonRpc"
    }, {
      "properties" : {
        "params" : {
          "type" : "object",
          "required" : [ "input" ], // <1>
          "properties" : {
            "input" : { // <1>
              "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Text" // <3>
            }
          }
        },
        "method" : {
          "type" : "string",
          "description" : "The method name",
          "example" : "testOperation"
        }
      }
    } ]
  },
 "OperationResponse" : {
    "allOf" : [ {
      "$ref" : "#/components/schemas/JsonRpc"
    }, {
      "properties" : {
        "result" : {
          "type" : "object",
          "required" : [ "output" ], // <2>
          "properties" : {
            "output" : { // <2>
              "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Text" // <4>
            }
          }
        }
      }
    } ]
  }
}
----

<1> the names of the input
<2> and output parameters are reflected in the properties generated for the request/response objects
<3> the characteristics are generated
<4> and referenced as described in the point 6 of the section "Mapping of Aspect and its properties"

As usual, corresponding entries referencing the definitions above are added to the `requestBodies` and `responses` sections (examples omitted for simplicity).
For technical reasons, there may be a slight variation in the generated JSON depending on whether the aspect has one or more operations defined.

==== Mapping of Collections

There are some additional JSON entries generated for complex types related to various types of collections to facilitate access to the individual elements of these collections via paging.
As these entries are rather of static character without direct references to any aspect elements, it suffices here to give a short overview about which kind of paging is available for which type of collection:

* a general Collection - cursor and/or offset based paging
* TimeSeries - cursor, offset and/or time based paging

For all these paging mechanisms, an additional entry with the name `PagingSchema` is generated in the `components/schemas` part of the specification,
which is then used as the main response schema for the Aspect. Basically, instead of a single Aspect, a collection of Aspects is returned,
together with optional total number of Aspects available in the collection:

[source,JSON]
----
"PagingSchema" : {
  "type" : "object",
  "properties" : {
    "items" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/Test"
      }
    },
    "totalItems" : {
      "type" : "number"
    }
  }
}
----

Depending on the concrete paging model selected, there can be additional properties in the `PagingSchema` object.
For cursor based paging, the `cursor` object denotes the position of the returned Aspects in relation to some other
uniquely identifiable Aspect (`before` or `after` it):

[source,JSON]
----
"cursor" : {
  "type" : "object",
  "properties" : {
    "before" : {
      "type" : "string",
      "format" : "uuid"
    },
    "after" : {
      "type" : "string",
      "format" : "uuid"
    }
  }
},
----

For offset and time based paging, the data is returned in batches of requested size ("pages"), described using the following properties (the meaning of which is self explanatory):

[source,JSON]
----
"totalPages" : {
  "type" : "number"
},
"pageSize" : {
  "type" : "number"
},
"currentPage" : {
  "type" : "number"
}
----

In addition to the `PagingSchema` object, also several new parameters are added to the request parameters section of the generated document,
with the help of which the size and/or the relative position of the returned data can be controlled.
All paging mechanisms have the following parameters in common, the meaning of which can be discerned from their descriptions:

[source,JSON]
----
{
  "name" : "count",
  "in" : "query",
  "description" : "Number of items to return per call.",
  "required" : false,
  "schema" : {
    "type" : "number"
  }
},
{
  "name" : "totalItemCount",
  "in" : "query",
  "description" : "Flag that indicates that the total counts should be returned.",
  "required" : false,
  "schema" : {
    "type" : "boolean"
  }
}
----

Depending on the exact paging model selected, additional paging specific parameters are available.
For offset based paging:
[source,JSON]
----
"name" : "start",
"in" : "query",
"description" : "Starting index which is starting by 0",
"required" : false,
"schema" : {
  "type" : "number"
}
----

For cursor based paging:
[source,JSON]
----
{
  "name" : "previous",
  "in" : "query",
  "description" : "URL to request the previous items. An empty value indicates there are no previous items.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "uri"
  }
},{
  "name" : "next",
  "in" : "query",
  "description" : "URL to request the next items. An empty value indicates there are no other items.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "uri"
    }
}, {
  "name" : "before",
  "in" : "query",
  "description" : "The cursor that points to the start of the page of items that has been returned.",
  "required" : false,
  "schema" : {
   "type" : "string",
    "format" : "uuid"
  }
}, {
  "name" : "after",
  "in" : "query",
  "description" : "The cursor that points to the end of items that has been returned.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "uuid"
  }
}
----

And finally for the time based paging:
[source,JSON]
----
{
  "name" : "since",
  "in" : "query",
  "description" : "A timestamp that points to the start of the time-based data.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "date-time"
  }
}, {
  "name" : "until",
  "in" : "query",
  "description" : "A timestamp that points to the end of the time-based data.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "date-time"
  }
}, {
  "name" : "limit",
  "in" : "query",
  "description" : "Number of items to return per call.",
  "required" : false,
    "schema" : {
    "type" : "number"
  }
}
----

[[models-directory-structure]]
== Understanding the models directory structure

An Aspect Model file can contain an Aspect definition as well as other model elements that are defined in the same versioned namespace, as described in the xref:samm-specification:ROOT:namespaces.adoc[Namespaces section of the
specification].
Additionally, it is possible to split one versioned namespace across multiple files, for example to define a Characteristic that is usable in multiple Aspects into its own file.
In order for SAMM CLI to be able to resolve references to such externally defined model elements, the model files must be organized in a directory structure as follows:

`_namespace_/_version_/_name_.ttl`

where _namespace_ corresponds to the hierarchical namespace that is part of the model element's URN, e.g.
`com.mycompany.myproduct` and _version_ corresponds to the version of the namespace.
The resulting directory structure then looks like the following:

[source,subs=+quotes]
----
_models root_
└── com.mycompany.myproduct
    ├── 1.0.0
    │   ├── MyAspect.ttl
    │   ├── MyEntity.ttl
    │   └── myProperty.ttl
    └── 1.1.0
        └── MyAspect.ttl
----

The name of the directory shown as _models root_ above can be chosen freely.
The SAMM CLI will resolve the file path relative to the input file by following the folder structure described above.
Each of the files in the `1.0.0` directory should therefore have an empty prefix declaration such as `@prefix : <urn:samm:com.mycompany.myproduct:1.0.0#>`.
