:page-partial:

[[samm-cli]]
= SAMM CLI

The SAMM CLI is a command line tool for the validation of Aspect Models and the generation of artifacts, such as documentation or code, from Aspect Models.

The SAMM CLI is available as a native executable for multiple platforms and as an executable jar:

[TIP]
.Downloading samm-cli
====
* Download executable for Windows (latest): https://github.com/eclipse-esmf/esmf-sdk/releases/download/v{esmf-sdk-version}/samm-cli-{esmf-sdk-version}-windows-x86_64.zip[samm-cli-{esmf-sdk-version}-windows-x86_64.zip]
* Download exectuable for Linux (latest): https://github.com/eclipse-esmf/esmf-sdk/releases/download/v{esmf-sdk-version}/samm-cli-{esmf-sdk-version}-linux-x86_64.tar.gz[samm-cli-{esmf-sdk-version}-linux-x86_64.tar.gz]
* Download executable jar for other platforms and architectures (latest): https://github.com/eclipse-esmf/esmf-sdk/releases/download/v{esmf-sdk-version}/samm-cli-{esmf-sdk-version}.jar[samm-cli-{esmf-sdk-version}.jar]. Running this version requires Java 17.
====

[[samm-cli-getting-started]]
== Running the SAMM CLI

For the executable jar, call `java -jar samm-cli-{esmf-sdk-version}.jar` followed by one of the following subcommands (e.g., `java -jar samm-cli-{esmf-sdk-version}.jar help`).
In the following sections, `samm` will be used as the command name.

[TIP]
====
To make `samm-cli` easier to call, you can add an alias to the configuration of the shell of your choice.
For example, for Bash, you could add the following line to `.bashrc`:

[source,shell,subs="attributes+,+quotes"]
----
alias samm='java -jar /location/to/samm-cli-{esmf-sdk-version}.jar'
----
====

. *For the Windows native executable:*
* *Download*: Download via above link or visit the repository of the Java SDK which contains the SAMM CLI at the Github https://github.com/eclipse-esmf/esmf-sdk/releases[releases page] and download executable file for Windows.
* *Extract*: extract it to a location of your choice.
* *Open* `samm.exe`: This will open a command prompt in this directory, where you can enter further `samm` commands.
* *Input*: Make sure to read the below documentation and provide model files in the correct xref:models-directory-structure[directory structure].

. *For the Linux native executable:*
* *Download*: Download via above link or visit the repository of the Java SDK which contains the SAMM CLI at the Github https://github.com/eclipse-esmf/esmf-sdk/releases[releases page] and download executable file for Linux.
* *Extract*: Unpack the archive to your preferred directory.
* *Open Terminal*: Open the Terminal and navigate to the directory with the application.
* *Input*: Make sure to read the below documentation and provide model files in the correct xref:models-directory-structure[directory structure].
* *Execute*: Run the application using the command `./samm`.

Successful execution of a command is signaled by returning 0. In case of a logical or other internal error the error code 1 is being returned.
Missing or wrong command parameters result in error code 2 being returned.

To get an overview of all commands and subcommands, use `samm help`.
To get help for a certain subcommand, use `help` before the subcommand name, e.g., `samm help aspect`, `samm help aspect validate` or `samm help aas to aspect`.
Each subcommand can have its own set of options which allow the user to further fine-tune the execution of the command.
The available options and their meaning can also be seen in the help text of the individual subcommands.

[width="100%",options="header",cols="20,50,30"]
|===
| Command | Description/Options | Examples
| help                             | Get overview of all commands                                                            | `samm help`
.3+| [[help]] help <commands...>   | Get help for a list of subcommands                                                      | `samm help aspect`
                                   |                                                                                         | `samm help aspect to svg`
                                   |                                                                                         | `samm help aspect validate`
.2+| [[aspect-validate]] aspect <model> validate | Validate Aspect Model                                                     | `samm aspect AspectModel.ttl validate`
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl validate --custom-resolver myresolver.sh`
.3+| [[aspect-prettyprint]] aspect <model> prettyprint | Pretty-print Aspect Model                                           | `samm aspect AspectModel.ttl prettyprint`
                                   | _--output, -o_ : the output will be saved to the given file                             | `samm aspect AspectModel.ttl prettyprint -o c:\Results\PrettyPrinted.ttl`
                                   | _--overwrite, -w_ : Overwrite the input file                                            | `samm aspect AspectModel.ttl prettyprint -w`
.5+| [[aspect-to-html]] aspect <model> to html | Generate HTML documentation for an Aspect Model                             | `samm aspect AspectModel.ttl to html`
                                   | _--output, -o_ : the output will be saved to the given file                             | `samm aspect AspectModel.ttl to html -o c:\Model.html`
                                   | _--css, -c_ : CSS file with custom styles to be included in the generated HTML
                                       documentation                                                                         | `samm aspect AspectModel.ttl to html -c c:\styles.css`
                                   | _--language, -l_ : The language from the model for which the HTML should be generated
                                       (default: en)                                                                         | `samm aspect AspectModel.ttl to html -l de`
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl to html --custom-resolver myresolver.bat`
.4+| [[aspect-to-png]] aspect <model> to png | Generate PNG diagram for Aspect Model                                         | `samm aspect AspectModel.ttl to png`
                                   | _--output, -o_ : output file path (default: stdout); as PNG is a binary format, it is
                                       strongly recommended to output the result to a file by using the -o option or the
                                       console redirection operator '>')|
                                   | _--language, -l_ : the language from the model for which the diagram should be
                                       generated (default: en)                                                               |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl to png --custom-resolver resolver.jar`
.4+| [[aspect-to-svg]] aspect <model> to svg | Generate SVG diagram for Aspect Model                                         | `samm aspect AspectModel.ttl to svg`
                                   | _--output, -o_ : the output will be saved to the given file                             |
                                   | _--language, -l_ : the language from the model for which the diagram should be
                                       generated (default: en)                                                               |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements | `samm aspect AspectModel.ttl to svg --custom-resolver "java -jar resolver.jar"`
.8+| [[asepct-to-java]] aspect <model> to java | Generate Java classes from an Aspect Model                                  | `samm aspect AspectModel.ttl to java`
                                   | _--output-directory, -d_ : output directory to write files to (default:
                                       current directory)                                                                    |
                                   | _--package-name, -pn_ : package to use for generated Java classes                       | `samm aspect AspectModel.ttl to java -pn org.company.product`
                                   | _--no-jackson, -nj_ : disable https://github.com/FasterXML/jackson[Jackson] annotation
                                       generation in generated Java classes                                                  |
                                   | _--template-library-file, -tlf_ : the path and name of the
                                       https://velocity.apache.org/[Velocity] template file containing the macro library     |
                                   | _--execute-library-macros, -elm_ : Execute the macros provided in the
                                       https://velocity.apache.org/[Velocity] macro library                                  |
                                   | _--static, -s_ : generate Java domain classes for a Static Meta Model                   |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.21+| [[aspect-to-openapi]] aspect <model> to openapi | Generate https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification
                                     for an Aspect Model                                                                     | `samm aspect AspectModel.ttl to openapi -j`
                                   | _--output, -o_ : output file path (default: stdout)                                     |
                                   | _--api-base-url, -b_ : the base url for the Aspect API used in the
                                       https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification                           | `samm aspect AspectModel.ttl to openapi -j -b \http://example.org`
                                   | _--json, -j_ : generate a JSON specification for an Aspect Model (default format
                                       is YAML)                                                                              |
                                   | _--comment, -c_ : only in combination with --json; generates `$comment`
                                       OpenAPI 3.1 keyword for all `samm:see` attributes                                     |
                                   | _--parameter-file, -p_ : the path to a file including the parameter for the Aspect
                                       API endpoints                                                                         | For detailed description, see the section bellow
                                   | _--semantic-version, -sv_ : use the full semantic version from the Aspect Model as the
                                       version for the Aspect API                                                            |
                                   | _--resource-path, -r_ : the resource path for the Aspect API endpoints                  | For detailed description, see the section bellow
                                   | _--include-query-api, -q_ : include the path for the Query Aspect API Endpoint in the
                                       https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification                           |
                                   | _--include-crud, -cr_ : include the POST/PUT/PATCH methods in the OpenAPI specification |
                                   | _--include-post, -post_ : include the POST method in the OpenAPI specification          |
                                   | _--include-put, -put_ : include the PUT method in the OpenAPI specification             |
                                   | _--include-patch, -patch_ : include the PATCH method in the OpenAPI specification       |
                                   | _--paging-none, -pn_ : exclude paging information for the Aspect API Endpoint in the
                                       https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification                           |
                                   | _--paging-cursor-based, -pc_ : in case there is more than one paging possibility,
                                       it must be cursor based paging                                                        |
                                   | _--paging-offset-based, -po_ : in case there is more than one paging possibility,
                                       it must be offset based paging                                                        |
                                   | _--paging-time-based, -pt_ : in case there is more than one paging possibility,
                                       it must be time based paging                                                          |
                                   | _--language, -l_ : The language from the model for which an OpenAPI specification should
                                       be generated (default: en)                                                            | `samm aspect AspectModel.ttl to openapi -l de`
                                   | _--template-file, -t_ : the path to a file including a template for
                                       the resulting specification, can be in JSON or YAML                                   | For detailed description, see the section bellow
                                   | _--separate-files, -sf_ : Create separate files for each schema                         |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.8+| [[aspect-to-asyncapi]] aspect <model> to asyncapi | Generate https://www.asyncapi.com/docs/reference/specification/v3.0.0[AsyncAPI] specification for an Aspect Model| `samm aspect AspectModel.ttl to asyncapi`
                                   | _--output, -o_ : output file path (default: stdout)                                     |
                                   | _--channel-address, -ca_ : Sets the channel address (i.e., for MQTT, the topic's name).
                                       https://spec.openapis.org/oas/v3.0.3[OpenAPI] specification                           | `samm aspect AspectModel.ttl to asyncapi -ca 123-456/789-012/namespace/1.0.0/Aspect`
                                   | _--application-id, -ai_ : Sets the application id, e.g. an identifying URL.             |
                                   | _--semantic-version, -sv_ : use the full semantic version from the Aspect Model as the
                                       version for the Aspect API                                                            |
                                   | _--language, -l_ : The language from the model for which an AsyncAPI specification should
                                       be generated (default: en)                                                            | `samm aspect AspectModel.ttl to asyncapi -l de`
                                   | _--separate-files, -sf_ : Create separate files for each schema                         |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.3+| [[aspect-to-json]] aspect <model> to json | Generate example JSON payload data for an Aspect Model                      | `samm aspect AspectModel.ttl to json`
                                   | _--output, -o_ : output file path (default: stdout)                                     |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.4+| [[aspect-to-schema]] aspect <model> to schema | Generate JSON schema for an Aspect Model                                | `samm aspect AspectModel.ttl to schema`
                                   | _--output, -o_ : output file path (default: stdout)                                     |
                                   | _--language, -l_ : The language from the model for which a JSON schema should be
                                       generated (default: en)                                                               | `samm aspect AspectModel.ttl to schema -l de`
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements |
.10+| [[aspect-to-sql]] aspect <model> to sql | Generate SQL script that sets up a table for data for this Aspect            | `samm aspect AspectModel.ttl to sql`
                                   | _--output, -o_ : output file path (default: stdout)                                     |
                                   | _--language, -l_ : The language from the model to use for generated comments            |
                                   | _--dialect, -d_ : The SQL dialect to generate for (default: `databricks`)               |
                                   | _--mapping-strategy, -s_ : The mapping strategy to use (default: `denormalized`)        |
                                   | _--include-table-comment, -tc_ : Include table comment in the generated SQL script
                                     (default: `true`)                                                                       |
                                   | _--include-column-comments, -cc_ : Include column comments in the generated SQL
                                     script (default: `true`)                                                                |
                                   | _--table-command-prefix, -tcp_ : The prefix to use for Databricks table creation
                                     commands (default: `CREATE TABLE IF NOT EXISTS`)                                        |
                                   | _--decimal-precision, -dp_ : The precision to use for Databricks decimal columns
                                     (default: 10). See also notes in
                                     the xref:java-aspect-tooling.adoc#databricks-type-mapping[Databricks type mapping].     |
                                   | _--custom-column, -col_ : Additional custom column definition, e.g. for databricks following the pattern `column_name DATATYPE [NOT NULL] [COMMENT 'custom']`. This parameter can be repeated for multiple columns.                                                  | `samm aspect AspectModel.ttl to sql --custom-column "column_name STRING NOT NULL COMMENT 'custom'"`
.5+| [[aspect-to-aas]] aspect <model> to aas | Generate an Asset Administration Shell (AAS) submodel template from an
                                     Aspect Model                                                                            | `samm aspect AspectModel.ttl to aas`
                                   | _--output, -o_ : output file path (default: stdout)                                     |
                                   | _--format, -f_ : output file format (xml, json, or aasx, default: xml)                  |
                                   | _--custom-resolver_ : use an external resolver for the resolution of the model elements |
                                   | _--aspect-data, -a_ : path to a JSON file containing aspect data corresponding to the
                                     Aspect Model                                                                            |
.5+| [[aspect-edit-move]] aspect <model> edit move <element> [<namespace>] | Move a model element definition from its
                                     current place to another existing or new file in the same or another namespace.         | `samm aspect AspectModel.ttl edit move
                                                                                                                                MyAspect otherFile.ttl` or `samm aspect
                                                                                                                                AspectModel.ttl edit move MyAspect
                                                                                                                                someFileInOtherNamespace.ttl
                                                                                                                                urn:samm:org.eclipse.example.myns:1.0.0`
                                   | _--dry-run_ : Don't write changes to the file system, but print a report of changes
                                     that would be performed.                                                                |
                                   | _--details_ : When used with `--dry-run`, include details about model content
                                     changes in the report .                                                                 |
                                   | _--copy-file-header_ : When a model element is moved to a new file, copy the file
                                     header from the source file to the new file                                             |
                                   | _--force_ : When a new file is to be created but it already exists in the file system,
                                     the operation will be cancelled, unless `--force` is used.                              |
.3+| [[aas-to-aspect]] aas <aas file> to aspect | Translate Asset Administration Shell (AAS) Submodel Templates to
                                     Aspect Models                                                                           | `samm aas AssetAdminShell.aasx to aspect`
                                   | _--output-directory, -d_ : output directory to write files to (default:
                                       current directory)                                                                    |
                                   | _--submodel-template, -s_ : selected submodel template for generating;
                                       run `samm aas <aas file> list` to list them.                                          | `samm aas AssetAdminShell.aasx to aspect -s 1 -s 2`
.1+| [[aas-list]] aas <aas file> list | Retrieve a list of submodel templates contained within the provided
                                       Asset Administration Shell (AAS) file.                                                | `samm aas AssetAdminShell.aasx list`

|===

=== Custom model resolver

To allow the users to provide their own custom implementations of a model resolver, `--custom-resolver` command-line switch can be used.
The value of the switch can be any command which is directly executable by the underlying operating system (such as a batch script on Windows or a shell script on Linux/Unix).
When a model element needs to be resolved, this command is executed with the URN of the element to resolve passed as the last parameter.
The command can provide other parameters as well, the element URN will be added automatically as the last one by samm-cli.
The resolved model definition is expected to be output to the stdout in Turtle format.
From there, it is read by the samm-cli and passed on to the internal processing pipeline.
In this way the extension can be flexibly done in any programming language/script language, including complex logic if necessary.

[[using-the-cli-to-create-a-json-openapi-specification]]
== Using the CLI to create a JSON OpenAPI Specification

Every specification is based on one Aspect, which needs a separately defined server URL where the given aspect will be.
The URL will be defined as string with the `-b` option, i.e.: https://www.example.org. The default URL, using the above
defined `--api-base-url`, would result in https://www.example.org/api/v1/\{tenantId}/<aspectName>. By default,
`\{tenantId}` followed by the Aspect's name is used as path, with the aspect name converted from CamelCase to
kebab-case. The default path can be changed with the `--resource-path` switch. If the path is defined further, for
example using `--resource-path "/resources/\{resourceId}"`, the resulting URL would be:
https://www.example.org/resources/\{resourceId}.

It will be required to specify the parameter, in case there is an additional parameter defined. This has to be done in
JSON or in YAML, depending on the kind of specification chosen. For example: With the option `--resource-path
"/resources/\{resourceId}"` the generator constructs the URL https://www.example.org/resources/\{resourceId} and then
the `--parameter-file` defines the parameter resourceId in YAML:

[source,yaml]
----
resourceId:
  name: resourceId
  in: path
  description: An example resource Id.
  required: true
  schema:
    type: string
----
Definitions of the parameters must correspond to the specification of the OpenAPI _Parameter Object_.

A template can be used for more specific customization - parameter `--template-file`.
The template is a document in the OpenAPI format, with one crucial difference - the presence of a templated Paths Object `paths.$$__DEFAULT_QUERIES_TEMPLATE__$$`.
All values not defined by the generator will be taken from the template.
For generator-defined Aspect Model resources, the values can be taken from the corresponding _Operation Object_ template `paths.$$__DEFAULT_QUERIES_TEMPLATE__$$`.

For example, the template file could look like this:

[source,yaml]
----
info:
  termsOfService: 'https://example.com/terms-of-service'

servers:
  - url: https://{environment}.example.com/api/v1
    variables:
      environment:
        default: api
        enum:
          - api
          - sandbox-api

components:
    responses:
      InternalServerError:
        description: An error occurred while processing the request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

paths:
  /status:
    get:
      tags:
        - Maintenance
      operationId: getHealthStatus
      description: Check the health status of the service.
      responses:
        "200":
          description: The service is up and running.
        "503":
            description: The service is down.

  __DEFAULT_QUERIES_TEMPLATE__:
    get:
      parameters:
        - name: request-id
          in: header
          description: The unique identifier for the request. If it isn't provided, it will be auto-generated.
          required: false
          schema:
            type: string
            format: uuid
      responses:
        "500":
          $ref: '#/components/responses/InternalServerError'
    post:
      parameters:
        - name: request-id
          in: header
          description: The unique identifier for the request. If it isn't provided, it will be auto-generated.
          required: false
          schema:
            type: string
            format: uuid


----

The full command for the native executable samm-cli would be:
[source,shell,subs="attributes+,+quotes"]
----
samm aspect _AspectModel.ttl_ to openapi -b "https://www.example.org" -r "/resources/\{resourceId}" -p _fileLocation_
----

For the Java version of samm-cli, the full command would result in:

[source,shell,subs="attributes+,+quotes"]
----
java -jar samm-cli-{esmf-sdk-version}.jar aspect _AspectModel.ttl_ to openapi -b "https://www.example.org" -r "/resources/\{resourceId}" -p _fileLocation_
----

=== Configuration of security schemas

For example, to configure OAuth2 authentication the template could look like this:

[source,yaml]
----
security:
  - OAuth2:
      - read:aspects

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://{environment}.example.com/oauth2/authorize
          tokenUrl: https://{environment}.example.com/oauth2/token
          scopes:
            read:aspects: Read access to aspects
            write:aspects: Write access to aspects

paths:
  __DEFAULT_QUERIES_TEMPLATE__:
    post:
      security:
        - OAuth2:
            - read:aspects
            - write:aspects

----

=== Mapping between the Aspect Models and the OpenAPI Specification

In this section, a detailed description of the mapping between individual Aspect elements and the OpenAPI specification is given.
To make it easier to follow, the mapping is explained based on a concrete example, divided into logically coherent blocks.
Please bear in mind that these blocks are snippets or fragments of a larger whole; viewed in isolation they do not necessarily form a valid or meaningful Aspect Model or OpenAPI specification.

==== Naming and versioning

Please consider the following model fragment, with the attention focused on the numbered elements:

[source,turtle,subs="attributes+,+quotes"]
----
@prefix : <urn:samm:{example-ns}.myapplication:1.0.0#> . # <1>
@prefix samm: <{samm}> .

:Test a samm:Aspect; # <3>
    samm:preferredName "TestAspect"@en ; # <2>
    samm:preferredName "TestAspekt"@de .
----

<1> prefix used to build the full URN of :Test Aspect
<2> the preferred name of the Aspect in language of user's choice
<3> the name of the Aspect

For the generated OpenAPI specification, the following mapping would apply:

[source,JSON]
----
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "TestAspect", // <2> <3>
    "version" : "v1" // <1>
  }
}
----

<1> depending on parameters used when generating the specification, this is either the major version of the full Aspect URN (*2*.0.0), or it can be the full version (`v2.0.0`), if using `-sv` (semantic version) command line switch
<2> if present, `samm:preferredName` is used as the value for the `title` element of the specification
<3> as `samm:preferredName` is an optional element, in cases when it is missing the name of the Aspect is used instead

The version information as described above is also used in the URL definitions of the `servers` block of the specification:

[source,JSON]
----
{
 "servers" : [ {
    "url" : "http://example.com/api/v1", // <1>
    "variables" : {
      "api-version" : {
        "default" : "v1" // <1>
      }
    }
  } ]
}
----

The name of the Aspect is used to generate several important OpenAPI artifacts, like the path definitions for the API:

[source,JSON]
----
{
 "paths" : {
    "/{tenant-id}/test" : { // <3>
      "get" : {
        "tags" : [ "Test" ], // <3>
        "operationId" : "getTest" // <3>
      }
    }
  }
}
----

and the definitions for request bodies and responses in the corresponding blocks (`requestBodies` and `responses`) of the OpenAPI specification (example omitted for simplicity).

==== Mapping of Aspect and its properties

For each Aspect in the model, an entry in the `components/schemas` part of the OpenAPI specification is generated.
For an example Aspect from the following fragment:

[source,turtle]
----
:Test a samm:Aspect; <1>
    samm:properties (
        :prop1 <2>
        [ samm:property :prop2; samm:payloadName "givenName"; ] <3>
        [ samm:property :prop3; samm:optional true; ] ). <4>

:prop1 a samm:Property;
    samm:description "Description of Property1"@en; <5>
    samm:characteristic :Enum. <6>
----

an entry like the one given in the following JSON will be generated:

[source,JSON]
----
"Test" : { // <1>
  "type" : "object",
    "properties" : {
      "prop1" : { // <2>
        "description" : "Description of Property1", // <5>
        "$ref" : "#/components/schemas/urn_samm_test_2.0.0_Enum" // <6>
      },
      "givenName" : { // <3>
        "$ref" : "#/components/schemas/urn_samm_test_2.0.0_EntityChar"
      },
      "prop3" : { // <4>
        "$ref" : "#/components/schemas/urn_samm_test_2.0.0_StringCharacteristic"
      }
    },
    "required" : [ "prop1", "givenName" ] // <2> <3>
}
----

<1> the name of the Aspect is used to name the schema object for the aspect
<2> with plain property references, the name of the property is used to name the property definition
<3> in cases where a payload name is defined on a specific property, it is used in preference to the plain property name
<4> if the property use is also defined as optional, the property will not be included in the list of the required properties
<5> the values of `samm:description` elements in property definitions are included in the generated JSON
<6> for each of the properties characteristics an entry in `components/schemas` is generated and referenced here; if the characteristic is of complex type, the whole procedure is applied recursively to the complex type's properties

==== Mapping of Aspect's operations

If the Aspect also has a non-empty list of operations defined, like the one in the following example:

[source,turtle]
----
:AspectWithOperation a samm:Aspect ;
   samm:properties ( ) ;
   samm:operations ( :testOperation ) .

:testOperation a samm:Operation ;
   samm:input ( :input ) ; <1>
   samm:output :output . <2>

:output a samm:Property ;
   samm:characteristic samm-c:Text . <3>

:input a samm:Property ;
   samm:characteristic samm-c:Text . <4>
----

then additional entries are added to the generated OpenAPI specification.
First, there is an additional entry in the `paths` section of the specification: `/{tenant-id}/aspect-with-operation/*operations*`.
The available operations are then added to the `components/schemas` part:

[source,JSON]
----
{
 "Operation" : {
    "allOf" : [ {
      "$ref" : "#/components/schemas/JsonRpc"
    }, {
      "properties" : {
        "params" : {
          "type" : "object",
          "required" : [ "input" ], // <1>
          "properties" : {
            "input" : { // <1>
              "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Text" // <3>
            }
          }
        },
        "method" : {
          "type" : "string",
          "description" : "The method name",
          "example" : "testOperation"
        }
      }
    } ]
  },
 "OperationResponse" : {
    "allOf" : [ {
      "$ref" : "#/components/schemas/JsonRpc"
    }, {
      "properties" : {
        "result" : {
          "type" : "object",
          "required" : [ "output" ], // <2>
          "properties" : {
            "output" : { // <2>
              "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_Text" // <4>
            }
          }
        }
      }
    } ]
  }
}
----

<1> the names of the input
<2> and output parameters are reflected in the properties generated for the request/response objects
<3> the characteristics are generated
<4> and referenced as described in the point 6 of the section "Mapping of Aspect and its properties"

As usual, corresponding entries referencing the definitions above are added to the `requestBodies` and `responses` sections (examples omitted for simplicity).
For technical reasons, there may be a slight variation in the generated JSON depending on whether the aspect has one or more operations defined.

==== Mapping of Collections

There are some additional JSON entries generated for complex types related to various types of collections to facilitate access to the individual elements of these collections via paging.
As these entries are rather of static character without direct references to any aspect elements, it suffices here to give a short overview about which kind of paging is available for which type of collection:

* a general Collection - cursor and/or offset based paging
* TimeSeries - cursor, offset and/or time based paging

For all these paging mechanisms, an additional entry with the name `PagingSchema` is generated in the `components/schemas` part of the specification,
which is then used as the main response schema for the Aspect. Basically, instead of a single Aspect, a collection of Aspects is returned,
together with optional total number of Aspects available in the collection:

[source,JSON]
----
"PagingSchema" : {
  "type" : "object",
  "properties" : {
    "items" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/Test"
      }
    },
    "totalItems" : {
      "type" : "number"
    }
  }
}
----

Depending on the concrete paging model selected, there can be additional properties in the `PagingSchema` object.
For cursor based paging, the `cursor` object denotes the position of the returned Aspects in relation to some other
uniquely identifiable Aspect (`before` or `after` it):

[source,JSON]
----
"cursor" : {
  "type" : "object",
  "properties" : {
    "before" : {
      "type" : "string",
      "format" : "uuid"
    },
    "after" : {
      "type" : "string",
      "format" : "uuid"
    }
  }
},
----

For offset and time based paging, the data is returned in batches of requested size ("pages"), described using the following properties (the meaning of which is self explanatory):

[source,JSON]
----
"totalPages" : {
  "type" : "number"
},
"pageSize" : {
  "type" : "number"
},
"currentPage" : {
  "type" : "number"
}
----

In addition to the `PagingSchema` object, also several new parameters are added to the request parameters section of the generated document,
with the help of which the size and/or the relative position of the returned data can be controlled.
All paging mechanisms have the following parameters in common, the meaning of which can be discerned from their descriptions:

[source,JSON]
----
{
  "name" : "count",
  "in" : "query",
  "description" : "Number of items to return per call.",
  "required" : false,
  "schema" : {
    "type" : "number"
  }
},
{
  "name" : "totalItemCount",
  "in" : "query",
  "description" : "Flag that indicates that the total counts should be returned.",
  "required" : false,
  "schema" : {
    "type" : "boolean"
  }
}
----

Depending on the exact paging model selected, additional paging specific parameters are available.
For offset based paging:
[source,JSON]
----
"name" : "start",
"in" : "query",
"description" : "Starting index which is starting by 0",
"required" : false,
"schema" : {
  "type" : "number"
}
----

For cursor based paging:
[source,JSON]
----
{
  "name" : "previous",
  "in" : "query",
  "description" : "URL to request the previous items. An empty value indicates there are no previous items.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "uri"
  }
},{
  "name" : "next",
  "in" : "query",
  "description" : "URL to request the next items. An empty value indicates there are no other items.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "uri"
    }
}, {
  "name" : "before",
  "in" : "query",
  "description" : "The cursor that points to the start of the page of items that has been returned.",
  "required" : false,
  "schema" : {
   "type" : "string",
    "format" : "uuid"
  }
}, {
  "name" : "after",
  "in" : "query",
  "description" : "The cursor that points to the end of items that has been returned.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "uuid"
  }
}
----

And finally for the time based paging:
[source,JSON]
----
{
  "name" : "since",
  "in" : "query",
  "description" : "A timestamp that points to the start of the time-based data.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "date-time"
  }
}, {
  "name" : "until",
  "in" : "query",
  "description" : "A timestamp that points to the end of the time-based data.",
  "required" : false,
  "schema" : {
    "type" : "string",
    "format" : "date-time"
  }
}, {
  "name" : "limit",
  "in" : "query",
  "description" : "Number of items to return per call.",
  "required" : false,
    "schema" : {
    "type" : "number"
  }
}
----

== Using the CLI to create a JSON AsyncAPI Specification

As with xref:using-the-cli-to-create-a-json-openapi-specification[OpenAPI], every AsyncAPI specification is based on one Aspect.
Each Aspect is associated with one https://www.asyncapi.com/docs/reference/specification/v3.0.0#channelObject[channel address].
The channel address is set as string using with`--channel-address` or `-ca` option, e.g.: `-ca 123-456/789-012/test/1.0.0/Aspect`. The default channel address
is derived from the Aspect's URN and is constructed using the pattern `{namespace}/\{version}/{aspectName}`.


The full command for the native executable samm-cli would be:
[source,shell,subs="attributes+,+quotes"]
----
samm aspect _AspectModel.ttl_ to asyncapi -ca "123-456/789-012/test/1.0.0/Aspect"
----

For the Java version of samm-cli, the corresponding full command is:

[source,shell,subs="attributes+,+quotes"]
----
java -jar samm-cli-{esmf-sdk-version}.jar aspect _AspectModel.ttl_ to asyncapi -ca "123-456/789-012/test/1.0.0/Aspect"
----

=== Mapping between the Aspect Models and the AsyncAPI Specification

In this section, a detailed description of the mapping between individual Aspect elements and the AsyncAPI specification is given.
To make it easier to follow, the mapping is explained based on a concrete example, divided into logically coherent blocks.
Please bear in mind that these blocks are snippets or fragments of a larger whole; viewed in isolation they do not necessarily form a valid or meaningful Aspect Model or AsyncAPI specification.

==== Naming and versioning

Please consider the following model fragment, with the attention focused on the numbered elements:

[source,turtle,subs="attributes+,+quotes"]
----
@prefix : <urn:samm:{example-ns}.myapplication:1.0.0#> . # <1>
@prefix samm: <{samm}> .

:Movement a samm:Aspect ; # <3>
   samm:name "Movement" ;
   samm:preferredName "My Movement Aspect"@en ; # <2>
   samm:description "Aspect for movement information"@en . # <4>
----

<1> prefix used to build the full URN of `:Movement` Aspect
<2> the preferred name of the Aspect in the language of the user's choice
<3> the name of the Aspect
<4> the description of the Aspect

For the generated AsyncAPI specification, the following mapping would apply:

[source,JSON]
----
{
  "asyncapi" : "3.0.0",
  "info" : {
    "title" : "My Movement Aspect MQTT API", // <2>
    "version" : "v1", // <1>
    "description" : "Aspect for movement information" // <3>
  }
}
----

<1> depending on parameters used when generating the specification, this is either the major version of the full Aspect URN (*2*.0.0), or it can be the full version (`v2.0.0`), if using `-sv` (semantic version) command line switch
<2> as `samm:preferredName` is used as the value for the `title` element of the specification (MQTT API defined automatically)
<3> as `samm:description` is an optional element

The name of the Aspect is used to generate parts of the AsyncAPI specification, such as the channel definitions for the API:

[source,JSON]
----
{
 "channels" : {
    "Movement" : { // <3>
      "address" : "movement/0.0.1/Movement", // <3>
      "description" : "This channel for updating Movement Aspect.", // <3>
      "parameters" : {
        "namespace" : "movement",
        "version" : "0.0.1",
        "aspect-name" : "Movement" // <3>
      },
      "messages" : {}
    }
  }
}
----

==== Mapping of Aspect's operations

The AsyncAPI specification is generated based on SAMM Operations and Events.
This section describes how specification parts are generated for Operations.
If the Aspect also has a non-empty list of Operations defined, such as the one in the following example:

[source,turtle]
----
:Movement a samm:Aspect ;
   samm:preferredName "movement"@en ;
   samm:description "Aspect for movement information"@en ;
   samm:properties ( ) ;
   samm:operations ( :getSpeed ) ;
   samm:events ( ) .

:getSpeed a samm:Operation ;
   samm:preferredName "Get speed"@en ;
   samm:description "Returns the current speed"@en ;
   samm:input ( :getSpeedInput ) ; # <1>
   samm:output :getSpeedOutput . # <2>

:getSpeedOutput a samm:Property ;
   samm:preferredName "getSpeed output"@en ;
   samm:description "Return value of the getSpeed operation"@en ;
   samm:characteristic :OutputCharacteristic .

:OutputCharacteristic a samm:Characteristic ;
   samm:preferredName "Output"@en ;
   samm:description "Describes the output of the getSpeed operation"@en ;
   samm:dataType :OutputEntity .

:OutputEntity a samm:Entity ;
   samm:preferredName "Output entity"@en ;
   samm:description "The structured response of getSpeed"@en ;
   samm:properties ( :outputEntityMessage ) .

:outputEntityMessage a samm:Property ;
   samm:characteristic samm-c:Text . # <3>

:getSpeedInput a samm:Property ;
   samm:preferredName "getSpeed input"@en ;
   samm:description "The input to the getSpeed operation"@en ;
   samm:characteristic samm-c:Text . # <4>
----

operations will be generated in some places of AsyncAPI specification:
https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObject[operations] section,
channel
https://www.asyncapi.com/docs/reference/specification/v3.0.0#messagesObject[messages] section and
https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject[schemas] section:

[source,JSON]
----
{
  "channels" : {
    "Movement" : {
      "address" : "movement/0.0.1/Movement",
      "description" : "This channel for updating Movement Aspect.",
      "parameters" : {
        "namespace" : "movement",
        "version" : "0.0.1",
        "aspect-name" : "Movement"
      },
      "messages" : {
        "getSpeedInput" : { // <1>
          "$ref" : "#/components/messages/getSpeedInput" // <1>
        },
        "getSpeedOutput" : { // <2>
          "$ref" : "#/components/messages/getSpeedOutput" // <2>
        }
      }
    }
  },
  "operations" : {
    "getSpeedInput" : {
      "action" : "receive", // <5>
      "channel" : {
        "$ref" : "#/channels/Movement"
      },
      "messages" : [ {
        "$ref" : "#/channels/Movement/messages/getSpeedInput" // <1>
      } ]
    },
    "getSpeedOutput" : { // <2>
      "action" : "send", // <5>
      "channel" : {
        "$ref" : "#/channels/Movement"
      },
      "messages" : [ {
        "$ref" : "#/channels/Movement/messages/getSpeedOutput" // <2>
      } ]
    }
  },
  "components" : {
    "messages" : {
      "getSpeedInput" : { // <1> <4>
        "name" : "getSpeedInput", // <1>
        "title" : "getSpeed input",
        "summary" : "The input to the getSpeed operation",
        "content-type" : "application/json",
        "payload" : {
          "$ref" : "#/components/schemas/getSpeedInput" // <1>
        }
      },
      "getSpeedOutput" : { // <2> <4>
        "name" : "getSpeedOutput", // <2>
        "title" : "getSpeed output",
        "summary" : "Return value of the getSpeed operation",
        "content-type" : "application/json",
        "payload" : {
          "$ref" : "#/components/schemas/getSpeedOutput" // <2>
        }
      }
    },
    "schemas" : {
      "getSpeedInput" : { // <1> <3>
        "type" : "string",
        "description" : "The input to the getSpeed operation"
      },
      "getSpeedOutput" : { // <2> <3>
        "type" : "string",
        "description" : "Return value of the getSpeed operation"
      }
    }
  }
}
----

<1> the names of the input
<2> the names of the output
<3> the characteristics are generated
<4> the meta information of input/output
<5> 'send' (for output) action: map to a publish operation in AsyncAPI, 'receive' (for input) action: map to a subscribe operation

==== Mapping of Aspect's events

This section describes the mapping between SAMM Events and the AsyncAPI specification.
If the Aspect also has a non-empty list of events defined, like the one in the following example:

[source,turtle]
----
:Movement a samm:Aspect ;
   samm:preferredName "movement"@en ;
   samm:description "Aspect for movement information"@en ;
   samm:properties ( ) ;
   samm:operations ( ) ;
   samm:events ( :SpeedUpdateEvent ) .

:SpeedUpdateEvent a samm:Event ;
   samm:preferredName "Speed Update"@en ;
   samm:description "This is event for update speed property"@en ;
   samm:parameters ( :updatedSpeed :updateAcceleration ) .

:updatedSpeed a samm:Property ;
   samm:preferredName "updated speed"@en ;
   samm:description "the updated speed value"@en ;
   samm:characteristic samm-c:Text .

:updateAcceleration a samm:Property ;
   samm:preferredName "update acceleration"@en ;
   samm:description "the updated acceleration value"@en ;
   samm:characteristic samm-c:Text .
----

events will be generated in some places of AsyncAPI specification:
https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObject[operations] section,
channel
https://www.asyncapi.com/docs/reference/specification/v3.0.0#messagesObject[messages] section and
https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject[schemas] section:

[source,JSON]
----
{
"channels" : {
    "Movement" : {
      "address" : "movement/0.0.1/Movement",
      "description" : "This channel for updating Movement Aspect.",
      "parameters" : {
        "namespace" : "movement",
        "version" : "0.0.1",
        "aspect-name" : "Movement"
      },
      "massages" : {
        "SpeedUpdateEvent" : {
          "$ref" : "#/components/messages/SpeedUpdateEvent" // <1>
        },
      }
    }
  },
  "operations" : {
    "SpeedUpdateEvent" : {
      "action" : "receive", // <5>
      "channel" : {
        "$ref" : "#/channels/Movement"
      },
      "messages" : [ {
        "$ref" : "#/channels/Movement/messages/SpeedUpdateEvent" // <1>
      } ]
    },
  },
  "components" : {
    "messages" : {
      "SpeedUpdateEvent" : { // <1> <2>
        "name" : "SpeedUpdateEvent", // <1>
        "title" : "Speed Update",
        "summary" : "This is event for update speed property",
        "content-type" : "application/json",
        "payload" : {
          "$ref" : "#/components/schemas/SpeedUpdateEvent" // <1>
        }
      }
    },
    "schemas" : {
      "SpeedUpdateEvent" : { // <1>
        "type" : "object",
        "properties" : {
          "updatedSpeed" : { // <3> <4>
            "title" : "updated speed",
            "type" : "string",
            "description" : "the updated speed value"
          },
          "updateAcceleration" : { // <3> <4>
            "title" : "updated acceleration",
            "type" : "string",
            "description" : "the updated acceleration value"
          }
        }
      }
    }
  }
}
----

<1> the names of the event
<2> the meta information of event
<3> property of event
<4> the characteristics are generated
<5> for events available only 'receive' action: map to a subscribe operation


[[models-directory-structure]]
== Understanding the models directory structure

An Aspect Model file can contain an Aspect definition as well as other model elements that are defined in the same versioned namespace, as described in the xref:samm-specification:ROOT:namespaces.adoc[Namespaces section of the
specification].
Additionally, it is possible to split one versioned namespace across multiple files, for example to define a Characteristic that is usable in multiple Aspects into its own file.
In order for SAMM CLI to be able to resolve references to such externally defined model elements, the model files must be organized in a directory structure as follows:

`_namespace_/_version_/_name_.ttl`

where _namespace_ corresponds to the hierarchical namespace that is part of the model element's URN, e.g.
`com.mycompany.myproduct` and _version_ corresponds to the version of the namespace.
The resulting directory structure then looks like the following:

[source,subs=+quotes]
----
_models root_
 com.mycompany.myproduct
     1.0.0
      MyAspect.ttl
      MyEntity.ttl
      myProperty.ttl
     1.1.0
         MyAspect.ttl
----

The name of the directory shown as _models root_ above can be chosen freely.
The SAMM CLI will resolve the file path relative to the input file by following the folder structure described above.
Each of the files in the `1.0.0` directory should therefore have an empty prefix declaration such as `@prefix : <urn:samm:com.mycompany.myproduct:1.0.0#>`.
