name: Check New Pull Request
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Run tests
      run: mvn clean test