name: Test

on:
  push:
    branches:
      - "pipeline-test"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/test.yaml"
  workflow_dispatch:

jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo -n "${CENTRAL_SONATYPE_TOKEN_USERNAME}" | base64
          echo -n "${CENTRAL_SONATYPE_TOKEN_PASSWORD}" | base64
