name: Test

on:
  workflow_dispatch:

jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo -n "${CENTRAL_SONATYPE_TOKEN_USERNAME}" | base64
          echo -n "${CENTRAL_SONATYPE_TOKEN_PASSWORD}" | base64
